/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AffiliateRouteImport } from './routes/_affiliate'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'
import { Route as AffiliatePortalRouteImport } from './routes/_affiliate.portal'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as LangTermsRouteImport } from './routes/$lang.terms'
import { Route as LangSuccessRouteImport } from './routes/$lang.success'
import { Route as LangRefundRouteImport } from './routes/$lang.refund'
import { Route as LangPrivacyRouteImport } from './routes/$lang.privacy'
import { Route as LangPreviewRouteImport } from './routes/$lang.preview'
import { Route as LangInputRouteImport } from './routes/$lang.input'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as AffiliatePortalIndexRouteImport } from './routes/_affiliate.portal.index'
import { Route as AdminDashboardIndexRouteImport } from './routes/_admin.dashboard.index'
import { Route as ApiPublicReconcileOrdersRouteImport } from './routes/api/public/reconcile-orders'
import { Route as ApiPublicLoveMatchStatusRouteImport } from './routes/api/public/love-match-status'
import { Route as ApiPublicLoveMatchRetryRouteImport } from './routes/api/public/love-match-retry'
import { Route as ApiPublicLoveMatchPriceRouteImport } from './routes/api/public/love-match-price'
import { Route as AffiliatePortalSalesRouteImport } from './routes/_affiliate.portal.sales'
import { Route as AffiliatePortalCouponsRouteImport } from './routes/_affiliate.portal.coupons'
import { Route as AdminDashboardSettingsRouteImport } from './routes/_admin.dashboard.settings'
import { Route as AdminDashboardPricingRouteImport } from './routes/_admin.dashboard.pricing'
import { Route as AdminDashboardOrdersRouteImport } from './routes/_admin.dashboard.orders'
import { Route as AdminDashboardFreeReportRouteImport } from './routes/_admin.dashboard.free-report'
import { Route as AdminDashboardFailuresRouteImport } from './routes/_admin.dashboard.failures'
import { Route as AdminDashboardCouponsRouteImport } from './routes/_admin.dashboard.coupons'
import { Route as AdminDashboardAffiliatesRouteImport } from './routes/_admin.dashboard.affiliates'

const AffiliateRoute = AffiliateRouteImport.update({
  id: '/_affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatePortalRoute = AffiliatePortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AffiliateRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const LangTermsRoute = LangTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LangRoute,
} as any)
const LangSuccessRoute = LangSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => LangRoute,
} as any)
const LangRefundRoute = LangRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => LangRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRoute,
} as any)
const LangPreviewRoute = LangPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => LangRoute,
} as any)
const LangInputRoute = LangInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const AffiliatePortalIndexRoute = AffiliatePortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AffiliatePortalRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const ApiPublicReconcileOrdersRoute =
  ApiPublicReconcileOrdersRouteImport.update({
    id: '/api/public/reconcile-orders',
    path: '/api/public/reconcile-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLoveMatchStatusRoute =
  ApiPublicLoveMatchStatusRouteImport.update({
    id: '/api/public/love-match-status',
    path: '/api/public/love-match-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLoveMatchRetryRoute = ApiPublicLoveMatchRetryRouteImport.update({
  id: '/api/public/love-match-retry',
  path: '/api/public/love-match-retry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLoveMatchPriceRoute = ApiPublicLoveMatchPriceRouteImport.update({
  id: '/api/public/love-match-price',
  path: '/api/public/love-match-price',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatePortalSalesRoute = AffiliatePortalSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AffiliatePortalRoute,
} as any)
const AffiliatePortalCouponsRoute = AffiliatePortalCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AffiliatePortalRoute,
} as any)
const AdminDashboardSettingsRoute = AdminDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardPricingRoute = AdminDashboardPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardOrdersRoute = AdminDashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardFreeReportRoute =
  AdminDashboardFreeReportRouteImport.update({
    id: '/free-report',
    path: '/free-report',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardFailuresRoute = AdminDashboardFailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardCouponsRoute = AdminDashboardCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardAffiliatesRoute =
  AdminDashboardAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AdminDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$lang': typeof LangRouteWithChildren
  '/': typeof AffiliateRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/input': typeof LangInputRoute
  '/$lang/preview': typeof LangPreviewRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/refund': typeof LangRefundRoute
  '/$lang/success': typeof LangSuccessRoute
  '/$lang/terms': typeof LangTermsRoute
  '/dashboard': typeof AdminDashboardRouteWithChildren
  '/portal': typeof AffiliatePortalRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/$lang/': typeof LangIndexRoute
  '/dashboard/affiliates': typeof AdminDashboardAffiliatesRoute
  '/dashboard/coupons': typeof AdminDashboardCouponsRoute
  '/dashboard/failures': typeof AdminDashboardFailuresRoute
  '/dashboard/free-report': typeof AdminDashboardFreeReportRoute
  '/dashboard/orders': typeof AdminDashboardOrdersRoute
  '/dashboard/pricing': typeof AdminDashboardPricingRoute
  '/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/portal/coupons': typeof AffiliatePortalCouponsRoute
  '/portal/sales': typeof AffiliatePortalSalesRoute
  '/api/public/love-match-price': typeof ApiPublicLoveMatchPriceRoute
  '/api/public/love-match-retry': typeof ApiPublicLoveMatchRetryRoute
  '/api/public/love-match-status': typeof ApiPublicLoveMatchStatusRoute
  '/api/public/reconcile-orders': typeof ApiPublicReconcileOrdersRoute
  '/dashboard/': typeof AdminDashboardIndexRoute
  '/portal/': typeof AffiliatePortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AffiliateRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/input': typeof LangInputRoute
  '/$lang/preview': typeof LangPreviewRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/refund': typeof LangRefundRoute
  '/$lang/success': typeof LangSuccessRoute
  '/$lang/terms': typeof LangTermsRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/$lang': typeof LangIndexRoute
  '/dashboard/affiliates': typeof AdminDashboardAffiliatesRoute
  '/dashboard/coupons': typeof AdminDashboardCouponsRoute
  '/dashboard/failures': typeof AdminDashboardFailuresRoute
  '/dashboard/free-report': typeof AdminDashboardFreeReportRoute
  '/dashboard/orders': typeof AdminDashboardOrdersRoute
  '/dashboard/pricing': typeof AdminDashboardPricingRoute
  '/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/portal/coupons': typeof AffiliatePortalCouponsRoute
  '/portal/sales': typeof AffiliatePortalSalesRoute
  '/api/public/love-match-price': typeof ApiPublicLoveMatchPriceRoute
  '/api/public/love-match-retry': typeof ApiPublicLoveMatchRetryRoute
  '/api/public/love-match-status': typeof ApiPublicLoveMatchStatusRoute
  '/api/public/reconcile-orders': typeof ApiPublicReconcileOrdersRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/portal': typeof AffiliatePortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$lang': typeof LangRouteWithChildren
  '/_admin': typeof AdminRouteWithChildren
  '/_affiliate': typeof AffiliateRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/input': typeof LangInputRoute
  '/$lang/preview': typeof LangPreviewRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/refund': typeof LangRefundRoute
  '/$lang/success': typeof LangSuccessRoute
  '/$lang/terms': typeof LangTermsRoute
  '/_admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/_affiliate/portal': typeof AffiliatePortalRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/$lang/': typeof LangIndexRoute
  '/_admin/dashboard/affiliates': typeof AdminDashboardAffiliatesRoute
  '/_admin/dashboard/coupons': typeof AdminDashboardCouponsRoute
  '/_admin/dashboard/failures': typeof AdminDashboardFailuresRoute
  '/_admin/dashboard/free-report': typeof AdminDashboardFreeReportRoute
  '/_admin/dashboard/orders': typeof AdminDashboardOrdersRoute
  '/_admin/dashboard/pricing': typeof AdminDashboardPricingRoute
  '/_admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/_affiliate/portal/coupons': typeof AffiliatePortalCouponsRoute
  '/_affiliate/portal/sales': typeof AffiliatePortalSalesRoute
  '/api/public/love-match-price': typeof ApiPublicLoveMatchPriceRoute
  '/api/public/love-match-retry': typeof ApiPublicLoveMatchRetryRoute
  '/api/public/love-match-status': typeof ApiPublicLoveMatchStatusRoute
  '/api/public/reconcile-orders': typeof ApiPublicReconcileOrdersRoute
  '/_admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_affiliate/portal/': typeof AffiliatePortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$lang'
    | '/'
    | '/$lang/contact'
    | '/$lang/input'
    | '/$lang/preview'
    | '/$lang/privacy'
    | '/$lang/refund'
    | '/$lang/success'
    | '/$lang/terms'
    | '/dashboard'
    | '/portal'
    | '/dashboard/login'
    | '/$lang/'
    | '/dashboard/affiliates'
    | '/dashboard/coupons'
    | '/dashboard/failures'
    | '/dashboard/free-report'
    | '/dashboard/orders'
    | '/dashboard/pricing'
    | '/dashboard/settings'
    | '/portal/coupons'
    | '/portal/sales'
    | '/api/public/love-match-price'
    | '/api/public/love-match-retry'
    | '/api/public/love-match-status'
    | '/api/public/reconcile-orders'
    | '/dashboard/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/contact'
    | '/$lang/input'
    | '/$lang/preview'
    | '/$lang/privacy'
    | '/$lang/refund'
    | '/$lang/success'
    | '/$lang/terms'
    | '/dashboard/login'
    | '/$lang'
    | '/dashboard/affiliates'
    | '/dashboard/coupons'
    | '/dashboard/failures'
    | '/dashboard/free-report'
    | '/dashboard/orders'
    | '/dashboard/pricing'
    | '/dashboard/settings'
    | '/portal/coupons'
    | '/portal/sales'
    | '/api/public/love-match-price'
    | '/api/public/love-match-retry'
    | '/api/public/love-match-status'
    | '/api/public/reconcile-orders'
    | '/dashboard'
    | '/portal'
  id:
    | '__root__'
    | '/$lang'
    | '/_admin'
    | '/_affiliate'
    | '/$lang/contact'
    | '/$lang/input'
    | '/$lang/preview'
    | '/$lang/privacy'
    | '/$lang/refund'
    | '/$lang/success'
    | '/$lang/terms'
    | '/_admin/dashboard'
    | '/_affiliate/portal'
    | '/dashboard/login'
    | '/$lang/'
    | '/_admin/dashboard/affiliates'
    | '/_admin/dashboard/coupons'
    | '/_admin/dashboard/failures'
    | '/_admin/dashboard/free-report'
    | '/_admin/dashboard/orders'
    | '/_admin/dashboard/pricing'
    | '/_admin/dashboard/settings'
    | '/_affiliate/portal/coupons'
    | '/_affiliate/portal/sales'
    | '/api/public/love-match-price'
    | '/api/public/love-match-retry'
    | '/api/public/love-match-status'
    | '/api/public/reconcile-orders'
    | '/_admin/dashboard/'
    | '/_affiliate/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LangRoute: typeof LangRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AffiliateRoute: typeof AffiliateRouteWithChildren
  DashboardLoginRoute: typeof DashboardLoginRoute
  ApiPublicLoveMatchPriceRoute: typeof ApiPublicLoveMatchPriceRoute
  ApiPublicLoveMatchRetryRoute: typeof ApiPublicLoveMatchRetryRoute
  ApiPublicLoveMatchStatusRoute: typeof ApiPublicLoveMatchStatusRoute
  ApiPublicReconcileOrdersRoute: typeof ApiPublicReconcileOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_affiliate': {
      id: '/_affiliate'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_affiliate/portal': {
      id: '/_affiliate/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AffiliatePortalRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/terms': {
      id: '/$lang/terms'
      path: '/terms'
      fullPath: '/$lang/terms'
      preLoaderRoute: typeof LangTermsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/success': {
      id: '/$lang/success'
      path: '/success'
      fullPath: '/$lang/success'
      preLoaderRoute: typeof LangSuccessRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/refund': {
      id: '/$lang/refund'
      path: '/refund'
      fullPath: '/$lang/refund'
      preLoaderRoute: typeof LangRefundRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/preview': {
      id: '/$lang/preview'
      path: '/preview'
      fullPath: '/$lang/preview'
      preLoaderRoute: typeof LangPreviewRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/input': {
      id: '/$lang/input'
      path: '/input'
      fullPath: '/$lang/input'
      preLoaderRoute: typeof LangInputRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/_affiliate/portal/': {
      id: '/_affiliate/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AffiliatePortalIndexRouteImport
      parentRoute: typeof AffiliatePortalRoute
    }
    '/_admin/dashboard/': {
      id: '/_admin/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/api/public/reconcile-orders': {
      id: '/api/public/reconcile-orders'
      path: '/api/public/reconcile-orders'
      fullPath: '/api/public/reconcile-orders'
      preLoaderRoute: typeof ApiPublicReconcileOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/love-match-status': {
      id: '/api/public/love-match-status'
      path: '/api/public/love-match-status'
      fullPath: '/api/public/love-match-status'
      preLoaderRoute: typeof ApiPublicLoveMatchStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/love-match-retry': {
      id: '/api/public/love-match-retry'
      path: '/api/public/love-match-retry'
      fullPath: '/api/public/love-match-retry'
      preLoaderRoute: typeof ApiPublicLoveMatchRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/love-match-price': {
      id: '/api/public/love-match-price'
      path: '/api/public/love-match-price'
      fullPath: '/api/public/love-match-price'
      preLoaderRoute: typeof ApiPublicLoveMatchPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_affiliate/portal/sales': {
      id: '/_affiliate/portal/sales'
      path: '/sales'
      fullPath: '/portal/sales'
      preLoaderRoute: typeof AffiliatePortalSalesRouteImport
      parentRoute: typeof AffiliatePortalRoute
    }
    '/_affiliate/portal/coupons': {
      id: '/_affiliate/portal/coupons'
      path: '/coupons'
      fullPath: '/portal/coupons'
      preLoaderRoute: typeof AffiliatePortalCouponsRouteImport
      parentRoute: typeof AffiliatePortalRoute
    }
    '/_admin/dashboard/settings': {
      id: '/_admin/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AdminDashboardSettingsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/pricing': {
      id: '/_admin/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof AdminDashboardPricingRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/orders': {
      id: '/_admin/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AdminDashboardOrdersRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/free-report': {
      id: '/_admin/dashboard/free-report'
      path: '/free-report'
      fullPath: '/dashboard/free-report'
      preLoaderRoute: typeof AdminDashboardFreeReportRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/failures': {
      id: '/_admin/dashboard/failures'
      path: '/failures'
      fullPath: '/dashboard/failures'
      preLoaderRoute: typeof AdminDashboardFailuresRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/coupons': {
      id: '/_admin/dashboard/coupons'
      path: '/coupons'
      fullPath: '/dashboard/coupons'
      preLoaderRoute: typeof AdminDashboardCouponsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/affiliates': {
      id: '/_admin/dashboard/affiliates'
      path: '/affiliates'
      fullPath: '/dashboard/affiliates'
      preLoaderRoute: typeof AdminDashboardAffiliatesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
  }
}

interface LangRouteChildren {
  LangContactRoute: typeof LangContactRoute
  LangInputRoute: typeof LangInputRoute
  LangPreviewRoute: typeof LangPreviewRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangRefundRoute: typeof LangRefundRoute
  LangSuccessRoute: typeof LangSuccessRoute
  LangTermsRoute: typeof LangTermsRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangContactRoute: LangContactRoute,
  LangInputRoute: LangInputRoute,
  LangPreviewRoute: LangPreviewRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangRefundRoute: LangRefundRoute,
  LangSuccessRoute: LangSuccessRoute,
  LangTermsRoute: LangTermsRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AdminDashboardRouteChildren {
  AdminDashboardAffiliatesRoute: typeof AdminDashboardAffiliatesRoute
  AdminDashboardCouponsRoute: typeof AdminDashboardCouponsRoute
  AdminDashboardFailuresRoute: typeof AdminDashboardFailuresRoute
  AdminDashboardFreeReportRoute: typeof AdminDashboardFreeReportRoute
  AdminDashboardOrdersRoute: typeof AdminDashboardOrdersRoute
  AdminDashboardPricingRoute: typeof AdminDashboardPricingRoute
  AdminDashboardSettingsRoute: typeof AdminDashboardSettingsRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardAffiliatesRoute: AdminDashboardAffiliatesRoute,
  AdminDashboardCouponsRoute: AdminDashboardCouponsRoute,
  AdminDashboardFailuresRoute: AdminDashboardFailuresRoute,
  AdminDashboardFreeReportRoute: AdminDashboardFreeReportRoute,
  AdminDashboardOrdersRoute: AdminDashboardOrdersRoute,
  AdminDashboardPricingRoute: AdminDashboardPricingRoute,
  AdminDashboardSettingsRoute: AdminDashboardSettingsRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AffiliatePortalRouteChildren {
  AffiliatePortalCouponsRoute: typeof AffiliatePortalCouponsRoute
  AffiliatePortalSalesRoute: typeof AffiliatePortalSalesRoute
  AffiliatePortalIndexRoute: typeof AffiliatePortalIndexRoute
}

const AffiliatePortalRouteChildren: AffiliatePortalRouteChildren = {
  AffiliatePortalCouponsRoute: AffiliatePortalCouponsRoute,
  AffiliatePortalSalesRoute: AffiliatePortalSalesRoute,
  AffiliatePortalIndexRoute: AffiliatePortalIndexRoute,
}

const AffiliatePortalRouteWithChildren = AffiliatePortalRoute._addFileChildren(
  AffiliatePortalRouteChildren,
)

interface AffiliateRouteChildren {
  AffiliatePortalRoute: typeof AffiliatePortalRouteWithChildren
}

const AffiliateRouteChildren: AffiliateRouteChildren = {
  AffiliatePortalRoute: AffiliatePortalRouteWithChildren,
}

const AffiliateRouteWithChildren = AffiliateRoute._addFileChildren(
  AffiliateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LangRoute: LangRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AffiliateRoute: AffiliateRouteWithChildren,
  DashboardLoginRoute: DashboardLoginRoute,
  ApiPublicLoveMatchPriceRoute: ApiPublicLoveMatchPriceRoute,
  ApiPublicLoveMatchRetryRoute: ApiPublicLoveMatchRetryRoute,
  ApiPublicLoveMatchStatusRoute: ApiPublicLoveMatchStatusRoute,
  ApiPublicReconcileOrdersRoute: ApiPublicReconcileOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
