/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as InputRouteImport } from './routes/input'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AffiliateRouteImport } from './routes/_affiliate'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'
import { Route as AffiliatePortalRouteImport } from './routes/_affiliate.portal'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AffiliatePortalIndexRouteImport } from './routes/_affiliate.portal.index'
import { Route as AdminDashboardIndexRouteImport } from './routes/_admin.dashboard.index'
import { Route as AffiliatePortalSalesRouteImport } from './routes/_affiliate.portal.sales'
import { Route as AffiliatePortalCouponsRouteImport } from './routes/_affiliate.portal.coupons'
import { Route as AdminDashboardSettingsRouteImport } from './routes/_admin.dashboard.settings'
import { Route as AdminDashboardPricingRouteImport } from './routes/_admin.dashboard.pricing'
import { Route as AdminDashboardOrdersRouteImport } from './routes/_admin.dashboard.orders'
import { Route as AdminDashboardFreeReportRouteImport } from './routes/_admin.dashboard.free-report'
import { Route as AdminDashboardFailuresRouteImport } from './routes/_admin.dashboard.failures'
import { Route as AdminDashboardCouponsRouteImport } from './routes/_admin.dashboard.coupons'
import { Route as AdminDashboardAffiliatesRouteImport } from './routes/_admin.dashboard.affiliates'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const InputRoute = InputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/_affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatePortalRoute = AffiliatePortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AffiliateRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AffiliatePortalIndexRoute = AffiliatePortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AffiliatePortalRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AffiliatePortalSalesRoute = AffiliatePortalSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AffiliatePortalRoute,
} as any)
const AffiliatePortalCouponsRoute = AffiliatePortalCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AffiliatePortalRoute,
} as any)
const AdminDashboardSettingsRoute = AdminDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardPricingRoute = AdminDashboardPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardOrdersRoute = AdminDashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardFreeReportRoute =
  AdminDashboardFreeReportRouteImport.update({
    id: '/free-report',
    path: '/free-report',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardFailuresRoute = AdminDashboardFailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardCouponsRoute = AdminDashboardCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardAffiliatesRoute =
  AdminDashboardAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AdminDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/input': typeof InputRoute
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AdminDashboardRouteWithChildren
  '/portal': typeof AffiliatePortalRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/affiliates': typeof AdminDashboardAffiliatesRoute
  '/dashboard/coupons': typeof AdminDashboardCouponsRoute
  '/dashboard/failures': typeof AdminDashboardFailuresRoute
  '/dashboard/free-report': typeof AdminDashboardFreeReportRoute
  '/dashboard/orders': typeof AdminDashboardOrdersRoute
  '/dashboard/pricing': typeof AdminDashboardPricingRoute
  '/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/portal/coupons': typeof AffiliatePortalCouponsRoute
  '/portal/sales': typeof AffiliatePortalSalesRoute
  '/dashboard/': typeof AdminDashboardIndexRoute
  '/portal/': typeof AffiliatePortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/input': typeof InputRoute
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/affiliates': typeof AdminDashboardAffiliatesRoute
  '/dashboard/coupons': typeof AdminDashboardCouponsRoute
  '/dashboard/failures': typeof AdminDashboardFailuresRoute
  '/dashboard/free-report': typeof AdminDashboardFreeReportRoute
  '/dashboard/orders': typeof AdminDashboardOrdersRoute
  '/dashboard/pricing': typeof AdminDashboardPricingRoute
  '/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/portal/coupons': typeof AffiliatePortalCouponsRoute
  '/portal/sales': typeof AffiliatePortalSalesRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/portal': typeof AffiliatePortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_affiliate': typeof AffiliateRouteWithChildren
  '/contact': typeof ContactRoute
  '/input': typeof InputRoute
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/_admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/_affiliate/portal': typeof AffiliatePortalRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/_admin/dashboard/affiliates': typeof AdminDashboardAffiliatesRoute
  '/_admin/dashboard/coupons': typeof AdminDashboardCouponsRoute
  '/_admin/dashboard/failures': typeof AdminDashboardFailuresRoute
  '/_admin/dashboard/free-report': typeof AdminDashboardFreeReportRoute
  '/_admin/dashboard/orders': typeof AdminDashboardOrdersRoute
  '/_admin/dashboard/pricing': typeof AdminDashboardPricingRoute
  '/_admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/_affiliate/portal/coupons': typeof AffiliatePortalCouponsRoute
  '/_affiliate/portal/sales': typeof AffiliatePortalSalesRoute
  '/_admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_affiliate/portal/': typeof AffiliatePortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/input'
    | '/preview'
    | '/privacy'
    | '/refund'
    | '/success'
    | '/terms'
    | '/dashboard'
    | '/portal'
    | '/dashboard/login'
    | '/dashboard/affiliates'
    | '/dashboard/coupons'
    | '/dashboard/failures'
    | '/dashboard/free-report'
    | '/dashboard/orders'
    | '/dashboard/pricing'
    | '/dashboard/settings'
    | '/portal/coupons'
    | '/portal/sales'
    | '/dashboard/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/input'
    | '/preview'
    | '/privacy'
    | '/refund'
    | '/success'
    | '/terms'
    | '/dashboard/login'
    | '/dashboard/affiliates'
    | '/dashboard/coupons'
    | '/dashboard/failures'
    | '/dashboard/free-report'
    | '/dashboard/orders'
    | '/dashboard/pricing'
    | '/dashboard/settings'
    | '/portal/coupons'
    | '/portal/sales'
    | '/dashboard'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_affiliate'
    | '/contact'
    | '/input'
    | '/preview'
    | '/privacy'
    | '/refund'
    | '/success'
    | '/terms'
    | '/_admin/dashboard'
    | '/_affiliate/portal'
    | '/dashboard/login'
    | '/_admin/dashboard/affiliates'
    | '/_admin/dashboard/coupons'
    | '/_admin/dashboard/failures'
    | '/_admin/dashboard/free-report'
    | '/_admin/dashboard/orders'
    | '/_admin/dashboard/pricing'
    | '/_admin/dashboard/settings'
    | '/_affiliate/portal/coupons'
    | '/_affiliate/portal/sales'
    | '/_admin/dashboard/'
    | '/_affiliate/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AffiliateRoute: typeof AffiliateRouteWithChildren
  ContactRoute: typeof ContactRoute
  InputRoute: typeof InputRoute
  PreviewRoute: typeof PreviewRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SuccessRoute: typeof SuccessRoute
  TermsRoute: typeof TermsRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input': {
      id: '/input'
      path: '/input'
      fullPath: '/input'
      preLoaderRoute: typeof InputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_affiliate': {
      id: '/_affiliate'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_affiliate/portal': {
      id: '/_affiliate/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AffiliatePortalRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_affiliate/portal/': {
      id: '/_affiliate/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AffiliatePortalIndexRouteImport
      parentRoute: typeof AffiliatePortalRoute
    }
    '/_admin/dashboard/': {
      id: '/_admin/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_affiliate/portal/sales': {
      id: '/_affiliate/portal/sales'
      path: '/sales'
      fullPath: '/portal/sales'
      preLoaderRoute: typeof AffiliatePortalSalesRouteImport
      parentRoute: typeof AffiliatePortalRoute
    }
    '/_affiliate/portal/coupons': {
      id: '/_affiliate/portal/coupons'
      path: '/coupons'
      fullPath: '/portal/coupons'
      preLoaderRoute: typeof AffiliatePortalCouponsRouteImport
      parentRoute: typeof AffiliatePortalRoute
    }
    '/_admin/dashboard/settings': {
      id: '/_admin/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AdminDashboardSettingsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/pricing': {
      id: '/_admin/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof AdminDashboardPricingRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/orders': {
      id: '/_admin/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AdminDashboardOrdersRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/free-report': {
      id: '/_admin/dashboard/free-report'
      path: '/free-report'
      fullPath: '/dashboard/free-report'
      preLoaderRoute: typeof AdminDashboardFreeReportRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/failures': {
      id: '/_admin/dashboard/failures'
      path: '/failures'
      fullPath: '/dashboard/failures'
      preLoaderRoute: typeof AdminDashboardFailuresRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/coupons': {
      id: '/_admin/dashboard/coupons'
      path: '/coupons'
      fullPath: '/dashboard/coupons'
      preLoaderRoute: typeof AdminDashboardCouponsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/affiliates': {
      id: '/_admin/dashboard/affiliates'
      path: '/affiliates'
      fullPath: '/dashboard/affiliates'
      preLoaderRoute: typeof AdminDashboardAffiliatesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
  }
}

interface AdminDashboardRouteChildren {
  AdminDashboardAffiliatesRoute: typeof AdminDashboardAffiliatesRoute
  AdminDashboardCouponsRoute: typeof AdminDashboardCouponsRoute
  AdminDashboardFailuresRoute: typeof AdminDashboardFailuresRoute
  AdminDashboardFreeReportRoute: typeof AdminDashboardFreeReportRoute
  AdminDashboardOrdersRoute: typeof AdminDashboardOrdersRoute
  AdminDashboardPricingRoute: typeof AdminDashboardPricingRoute
  AdminDashboardSettingsRoute: typeof AdminDashboardSettingsRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardAffiliatesRoute: AdminDashboardAffiliatesRoute,
  AdminDashboardCouponsRoute: AdminDashboardCouponsRoute,
  AdminDashboardFailuresRoute: AdminDashboardFailuresRoute,
  AdminDashboardFreeReportRoute: AdminDashboardFreeReportRoute,
  AdminDashboardOrdersRoute: AdminDashboardOrdersRoute,
  AdminDashboardPricingRoute: AdminDashboardPricingRoute,
  AdminDashboardSettingsRoute: AdminDashboardSettingsRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AffiliatePortalRouteChildren {
  AffiliatePortalCouponsRoute: typeof AffiliatePortalCouponsRoute
  AffiliatePortalSalesRoute: typeof AffiliatePortalSalesRoute
  AffiliatePortalIndexRoute: typeof AffiliatePortalIndexRoute
}

const AffiliatePortalRouteChildren: AffiliatePortalRouteChildren = {
  AffiliatePortalCouponsRoute: AffiliatePortalCouponsRoute,
  AffiliatePortalSalesRoute: AffiliatePortalSalesRoute,
  AffiliatePortalIndexRoute: AffiliatePortalIndexRoute,
}

const AffiliatePortalRouteWithChildren = AffiliatePortalRoute._addFileChildren(
  AffiliatePortalRouteChildren,
)

interface AffiliateRouteChildren {
  AffiliatePortalRoute: typeof AffiliatePortalRouteWithChildren
}

const AffiliateRouteChildren: AffiliateRouteChildren = {
  AffiliatePortalRoute: AffiliatePortalRouteWithChildren,
}

const AffiliateRouteWithChildren = AffiliateRoute._addFileChildren(
  AffiliateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AffiliateRoute: AffiliateRouteWithChildren,
  ContactRoute: ContactRoute,
  InputRoute: InputRoute,
  PreviewRoute: PreviewRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SuccessRoute: SuccessRoute,
  TermsRoute: TermsRoute,
  DashboardLoginRoute: DashboardLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
